# Linked to /etc/nix/nix.custom.conf by `just nix`, included by the
# Determinate-managed /etc/nix/nix.conf.
trusted-users = root mkurde

# garnix cache, serves prebuilt Emanote
extra-substituters = https://cache.garnix.io
extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
