tap "homebrew/bundle"
tap "homebrew/services"
# Trusted taps (brew trust). Not in homebrew-core:
tap "johanhaleby/kubetail"
tap "little-angry-clouds/my-brews"
tap "my-monkeys/tap"
tap "mykso/tap"
tap "nats-io/nats-tools"
tap "redpanda-data/tap"
tap "stablyai/orca"

brew "autojump"
brew "bash"
brew "bat"
brew "cheat"
brew "coreutils"
brew "dep"
brew "direnv"
brew "dive"
brew "doctl"
brew "fzf"
brew "git"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnupg"
brew "gnutls"
brew "go"
brew "grep"
brew "gron"
brew "gh"
brew "little-angry-clouds/my-brews/helmenv"
brew "htop"
brew "ipcalc"
brew "istioctl"
brew "icu4c" # https://github.com/mickael-menu/zk
brew "jq"
brew "just"
brew "k3d"
brew "k9s"
# brew "kafkacat" # deprecated in favour of kcat
brew "kapp"
brew "kbld"
brew "kcat"
brew "kubectx"
brew "kubefwd"
brew "kubernetes-cli", link: false
brew "johanhaleby/kubetail/kubetail"
brew "kubie"
brew "kdash"
brew "lazydocker"
brew "lazygit"
brew "make"
brew "mas"
brew "mise"
brew "moreutils"
brew "nats-io/nats-tools/nats"
brew "redpanda-data/tap/redpanda"
brew "ngrep"
brew "nushell"
brew "pinentry-mac"
brew "plantuml"
brew "popeye"
brew "pre-commit"
brew "prips"
brew "rancher-cli"
brew "restic"
brew "shellcheck"
brew "slides"
brew "starship"
brew "stern"
brew "stow"
brew "telnet"
brew "terraform-docs"
brew "tfenv"
brew "tgenv"
brew "tflint"
brew "tfmigrate"
brew "tfsec"
brew "tfstate-lookup"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "xz"
brew "yq"
brew "zsh"
brew "zoxide"

cask "mykso/tap/myks"
cask "my-monkeys/tap/opensuperwhisper"
cask "stablyai/orca/orca"
cask "orbstack"
cask "1password"
cask "1password-cli"
cask "bettertouchtool"
cask "claude"
cask "claude-code"
cask "cursor"
cask "cursor-cli"
cask "bloomrpc"
cask "dash"
# cask "docker-toolbox" # discontinued
cask "opera-gx"
cask "firefox"
cask "firefox@developer-edition"
cask "gimp"
cask "google-chrome"
cask "gcloud-cli"
# cask "gpg-suite"
cask "istat-menus"
cask "iterm2"
# cask "joplin"
cask "openlogi"
# cask "logitech-options"
cask "logitech-camera-settings"
cask "sequel-ace"
cask "spotify"
cask "spotmenu"
cask "rectangle"
# cask "teamviewer"
# cask "teamviewer-quickjoin"
# cask "teamviewer-quicksupport"
cask "the-unarchiver"
cask "visual-studio-code"
# cask "vlc"
cask "wireshark-app"

# mas "Kaleidoscope", id: 587512244
