tap "homebrew/bundle"
tap "homebrew/services"
# Trusted taps (brew trust). Not in homebrew-core:
tap "little-angry-clouds/my-brews"
tap "nklmilojevic/sofka"
tap "my-monkeys/tap"
tap "mykso/tap"
tap "nats-io/nats-tools"
tap "redpanda-data/tap"
tap "stablyai/orca"

brew "argocd"
brew "bash"
brew "bat"
brew "biome"
brew "cheat"
brew "coreutils"
brew "crane"
brew "curl"
brew "diff-so-fancy"
brew "direnv"
brew "doctl"
brew "emacs"
brew "eza"
brew "fd"
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "git-lfs"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnupg"
brew "gnutls"
brew "go"
brew "graphviz"
brew "grep"
brew "little-angry-clouds/my-brews/helmenv"
brew "htop"
brew "iperf3"
brew "istioctl"
brew "k3d"
brew "k9s"
brew "kafka"
brew "kapp"
brew "kbld"
brew "kdash"
brew "kubectx"
brew "kubefwd"
brew "kubernetes-cli", link: false
brew "kubie"
brew "lazydocker"
brew "lazygit"
brew "make"
brew "mas"
brew "mise"
brew "moreutils"
brew "nats-io/nats-tools/nats"
brew "ngrep"
brew "nushell"
brew "openjdk@21"
brew "pinentry-mac"
brew "popeye"
brew "prips"
brew "rancher-cli"
brew "redis"
brew "redpanda-data/tap/redpanda"
brew "restic"
brew "resticprofile"
brew "ripgrep"
brew "rust"
brew "skopeo"
brew "nklmilojevic/sofka/sofka"
brew "starship"
brew "stern"
brew "telnet"
brew "tfstate-lookup"
brew "tmux"
brew "tree"
brew "uv"
brew "vim"
brew "volta"
brew "watch"
brew "wget"
brew "xz"
brew "zk"
brew "zookeeper"
brew "zoxide"
brew "zsh"

cask "1password"
cask "1password-cli"
cask "bettertouchtool"
cask "caffeine"
cask "cameracontroller"
cask "claude"
cask "claude-code@latest"
cask "copilot-cli"
cask "cursor"
cask "cursor-cli"
cask "dash"
cask "firefox"
cask "firefox@developer-edition"
cask "gcloud-cli"
cask "gimp"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
# cask "joplin"
cask "lens"
# cask "logitech-camera-settings" # replaced with cameracontroller
# cask "logitech-options" # not needed, MX Vertical works without a driver
cask "mykso/tap/myks"
cask "ngrok"
# cask "opensuperwhisper" # unmaintained (starmel/OpenSuperWhisper), use my-monkeys/tap instead
cask "my-monkeys/tap/opensuperwhisper"
cask "opera-gx"
cask "orbstack"
cask "stablyai/orca/orca"
cask "rectangle"
cask "sequel-ace"
cask "skills-manager"
cask "spotify"
cask "spotmenu"
cask "tailscale-app"
# cask "teamviewer"
# cask "teamviewer-quickjoin"
# cask "teamviewer-quicksupport"
cask "the-unarchiver"
cask "ticktick"
cask "visual-studio-code"
# cask "vlc"
cask "wireshark-app"

# Installed by company tooling, not via Homebrew: obsidian, slack

# mas "Kaleidoscope", id: 587512244
